### ISSUE TITLE
Adding Suffixes

### ISSUE THREAD

**Issue by DavidSSchwartz** [mklaber/node-another-name-parser#20]
I would like to add suffixes to the suffix list.
I already cloned the repo and made a branch but need permission to push and open a PR.
Here is the proposed change:

var suffixes = [
  'CCSP', 'CPA', 'DC', 'DDS', 'DMD', 'DO', 'DPM', 'DVM', 'ESQ', 'ESTATE',
  'FAM', 'FAMILY', 'II', 'III', 'IV', 'JR', 'LUTCF', 'MD', 'OC', 'OD', 'PA',
  'PE', 'PHD', 'SJ', 'SR', 'V', 'VI', 'VP', 'V', 'I', 'VI', 'VII', 'VIII',
  'CNP', 'CPA', 'DDS', 'DMin', 'DMA ', 'DMus', 'OD', 'DO', 'PharmD', 'PhD',
  'PsyD', 'DVM', 'EI', 'EIT', 'Esq', 'JD', 'LLS', 'LP', 'LPN',
  'MD', 'PE', 'RA', 'RLA', 'RLS', 'RN', 'SE', 'ESQUIRE', **'MSW', 'LCSW', 'ACSW', 
  'ASW', 'PPSC', 'BSc', 'MBA', 'BSW', 'BSN', 'CHPN', 'MSN', 'CCRN', 'MSc'**
];

**Comment by mklaber** [comment]
@DavidSSchwartz did you clone or fork? If you fork, you should be able to open a PR (example [here](https://github.com/mklaber/node-another-name-parser/pull/3)).
