### ISSUE TITLE
has vulnerable dependency.. can we get dependency updated?

### ISSUE THREAD

**Issue by rajkumar-mariselvaraj** [mklaber/node-another-name-parser#5]
Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   another-name-parser

  Path            another-name-parser > lodash

  More info       https://nodesecurity.io/advisories/577

**Comment by mklaber** [comment]
@rajkumar-mariselvaraj sure, submit a pull request?

**Comment by mklaber** [comment]
Whoops. This was fixed in #4 but I neglected to publish the update to npm. It's there now and should resolve this issue.
